apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.interactsh.service.name }}
  labels:
    {{- include "vulmap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.interactsh.service.type }}
  ports:
    - port: {{ .Values.interactsh.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vulmap.selectorLabels" . | nindent 4 }}
